language: python
install:
- pip install mkdocs mkdocs-material
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GH_TOKEN
 local_dir: site
 on:
   branch: master
